# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ODA Trading System' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ODA Trading System
pod 'Charts'

  target 'ODA Trading SystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ODA Trading SystemUITests' do
    # Pods for testing
  end

end
